"""initial

Revision ID: 9c6eebecffb5
Revises: 
Create Date: 2025-04-18 09:58:19.595690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c6eebecffb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_assignment_section', table_name='assignment')
    op.drop_constraint('assignment_ibfk_1', 'assignment', type_='foreignkey')
    op.create_foreign_key(None, 'assignment', 'teacher', ['teacher_id'], ['id'])
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'])
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key('assignment_ibfk_1', 'assignment', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_assignment_section', 'assignment', ['section'], unique=False)
    op.drop_table('discussion_post')
    op.drop_table('message')
    op.drop_table('discussion_thread')
    # ### end Alembic commands ###
